### ISSUE TITLE
NEEDZ MORE PICS

### ISSUE THREAD

**Issue by waxidiotic** [DanFCo/personal#1]
totes

**Comment by waxidiotic** [comment]
aNy UpD@tes?

**Comment by DanFCo** [comment]
lol...where are these being sent from? and no no updates... just been
working on the brewery thing lol
i can't seem to get the github pages to work with my hover domain... it'll
work if you type in https://dan-correia.com but not www.dan-correia.com

**Comment by waxidiotic** [comment]
https://github.com/DanFCo/personal/issues/1

**Comment by DanFCo** [comment]
i'll try to resolve this issue sir. i apologize for the delay

**Comment by DanFCo** [comment]
listen here gritty, i'm doing my best
